// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";

function Test(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, "Hello2 Andrea"), root);
}

var make = Test;

export {
  make ,
  
}
/* root Not a pure module */
